# -*- coding: utf-8 -*-
"""消息属性键常量（对应 org.apache.rocketmq.common.message.MessageConst）。"""
from __future__ import annotations


class MessageConst:
    PROPERTY_KEYS = "KEYS"
    PROPERTY_TAGS = "TAGS"
    PROPERTY_WAIT_STORE_MSG_OK = "WAIT"
    PROPERTY_DELAY_TIME_LEVEL = "DELAY"
    PROPERTY_RETRY_TOPIC = "RETRY_TOPIC"
    PROPERTY_REAL_TOPIC = "REAL_TOPIC"
    PROPERTY_REAL_QUEUE_ID = "REAL_QID"
    PROPERTY_TRANSACTION_PREPARED = "TRAN_MSG"
    PROPERTY_PRODUCER_GROUP = "PGROUP"
    PROPERTY_MIN_OFFSET = "MIN_OFFSET"
    PROPERTY_MAX_OFFSET = "MAX_OFFSET"
    PROPERTY_BUYER_ID = "BUYER_ID"
    PROPERTY_ORIGIN_MESSAGE_ID = "ORIGIN_MESSAGE_ID"
    PROPERTY_TRANSFER_FLAG = "TRANSFER_FLAG"
    PROPERTY_CHECK_IMMUNITY_TIME_IN_SECONDS = "CHECK_IMMUNITY_TIME_IN_SECONDS"
    PROPERTY_RECONSUME_TIME = "RECONSUME_TIME"
    PROPERTY_MSG_REGION = "MSG_REGION"
    PROPERTY_UNIQ_CLIENT_MESSAGE_ID_KEYIDX = "UNIQ_KEY"
    PROPERTY_MAX_RECONSUME_TIMES = "MAX_RECONSUME_TIMES"
    PROPERTY_CONSUME_START_TIMESTAMP = "CONSUME_START_TIME"

    PROPERTY_TRANSACTION_PREPARED_QUEUE_OFFSET = "TRAN_PREPARED_QUEUE_OFFSET"
    PROPERTY_TRANSACTION_CHECK_TIMES = "TRANSACTION_CHECK_TIMES"
    PROPERTY_CHECKED_TOPIC = "CHECKED_TOPIC"
    PROPERTY_BORN_HOST = "BORN_HOST"
    PROPERTY_BORN_TIMESTAMP = "BORN_TIMESTAMP"
    PROPERTY_STORE_HOST = "STORE_HOST"
    PROPERTY_STORE_TIMESTAMP = "STORE_TIMESTAMP"
    PROPERTY_MSG_ID = "MSG_ID"
    PROPERTY_WAIT_STORE_MSG_OK_PROP = "WAIT_STORE_MSG_OK"
    PROPERTY_INSTANCE_ID = "INSTANCE_ID"
    PROPERTY_CLUSTER = "CLUSTER"
    PROPERTY_MESSAGE_TYPE = "MSG_TYPE"
    # Request-Reply（5.x）：请求消息带 CORRELATION_ID/REPLY_TO_CLIENT/TTL，
    # 应答方（消费者）回一条 MSG_TYPE="reply" 的消息，broker 按 REPLY_TO_CLIENT
    # 把应答推回请求方的 PUSH_REPLY_MESSAGE_TO_CLIENT(326) 通道。
    PROPERTY_CORRELATION_ID = "CORRELATION_ID"
    PROPERTY_MESSAGE_REPLY_TO_CLIENT = "REPLY_TO_CLIENT"
    PROPERTY_MESSAGE_TTL = "TTL"
    PROPERTY_REPLY_MESSAGE_ARRIVE_TIME = "REPLY_MESSAGE_ARRIVE_TIME"
    PROPERTY_PUSH_REPLY_TIME = "PUSH_REPLY_TIME"
    PROPERTY_INNER_MULTI_DISPATCH = "INNER_MULTI_DISPATCH"
    PROPERTY_INNER_MULTI_QUEUE_OFFSET = "INNER_MULTI_QUEUE_OFFSET"
    PROPERTY_POP_CK = "POP_CK"
    PROPERTY_POP_CK_OFFSET = "POP_CK_OFFSET"
    PROPERTY_POP_TIME = "POP_TIME"
    PROPERTY_INVISIBLE_TIME = "INVISIBLE_TIME"
    PROPERTY_DELAY_TIME = "DELAY_TIME"
    PROPERTY_START_TIME = "START_TIME"
    PROPERTY_END_TIME = "END_TIME"
    PROPERTY_EXPIRE_TIME = "EXPIRE_TIME"
    PROPERTY_LAST_CONSUME_TIMESTAMP = "LAST_CONSUME_TIME"
    PROPERTY_SELF_CONSUME_ENABLE = "SELF_CONSUME"
    PROPERTY_RECONSUME_GROUP = "RECONSUME_GROUP"
    PROPERTY_RECONSUME_TOPIC = "RECONSUME_TOPIC"
    PROPERTY_KEYS_CONST = "KEYS"
    PROPERTY_ORIGIN_QUEUE_ID = "ORIGIN_QID"
    PROPERTY_ORIGIN_TOPIC = "ORIGIN_TOPIC"

    STRING_HASH_SET = 1

    KEY_SEPARATOR = " "
    KEY_SEPARATOR_CHAR = " "
    CHARACTER_MAX_LENGTH = 255
    MESSAGE_ID_PREFIX = "MSGID-"

    # 索引查询类型（对应 MessageConst.INDEX_KEY_TYPE / INDEX_UNIQUE_TYPE / INDEX_TAG_TYPE）
    # broker 的 QueryMessageRequestHeader.indexType 取这些值；为空时 broker 按 "K" 处理。
    INDEX_KEY_TYPE = "K"
    INDEX_UNIQUE_TYPE = "U"
    INDEX_TAG_TYPE = "T"

    @staticmethod
    def message_id_prefix() -> str:
        return MessageConst.MESSAGE_ID_PREFIX