package common

import "testing"

// The vectors below were generated by running the Python reference
// (rocketmq.remoting.protocol.namespace_util.NamespaceUtil) so the Go port is
// pinned to the same answers, not to a re-reading of the Java source.

func TestWrapNamespaceVectorsMatchPython(t *testing.T) {
	cases := []struct {
		namespace, resource, want string
	}{
		{"ns1", "TopicA", "ns1%TopicA"},
		// %RETRY%/%DLQ% stay OUTSIDE the namespace.
		{"ns1", "%RETRY%GID", "%RETRY%ns1%GID"},
		{"ns1", "%DLQ%GID", "%DLQ%ns1%GID"},
		// idempotent
		{"ns1", "ns1%TopicA", "ns1%TopicA"},
		// system resources are never namespaced
		{"ns1", "rmq_sys_x", "rmq_sys_x"},
		{"ns1", "CID_RMQ_SYS_g", "CID_RMQ_SYS_g"},
		// empty either side is a no-op
		{"ns1", "", ""},
		{"", "TopicA", "TopicA"},
	}
	for _, c := range cases {
		if got := WrapNamespace(c.namespace, c.resource); got != c.want {
			t.Fatalf("WrapNamespace(%q, %q) = %q, want %q", c.namespace, c.resource, got, c.want)
		}
	}
}

func TestWithoutNamespaceVectorsMatchPython(t *testing.T) {
	cases := []struct {
		resource, namespace, want string
	}{
		{"MQ_INST_XX%TopicA", "", "TopicA"},
		{"%RETRY%MQ_INST_XX%GID", "", "%RETRY%GID"},
		{"%DLQ%MQ_INST_XX%GID", "", "%DLQ%GID"},
		{"rmq_sys_x", "", "rmq_sys_x"},
		{"TopicA", "", "TopicA"},
		{"MQ_INST_XX%TopicA", "MQ_INST_XX", "TopicA"},
		// a non-matching namespace leaves the resource untouched
		{"MQ_INST_YY%TopicA", "MQ_INST_XX", "MQ_INST_YY%TopicA"},
		// no separator left after stripping the retry prefix -> unchanged
		{"%RETRY%GID", "", "%RETRY%GID"},
	}
	for _, c := range cases {
		if got := WithoutNamespace(c.resource, c.namespace); got != c.want {
			t.Fatalf("WithoutNamespace(%q, %q) = %q, want %q", c.resource, c.namespace, got, c.want)
		}
	}
}

func TestNamespaceRoundTrip(t *testing.T) {
	for _, resource := range []string{"TopicA", "%RETRY%GID", "%DLQ%GID", "CID_x-1"} {
		wrapped := WrapNamespace("ns1", resource)
		if got := WithoutNamespace(wrapped, "ns1"); got != resource {
			t.Fatalf("round trip %q: wrapped %q, unwrapped %q", resource, wrapped, got)
		}
	}
}

func TestIsSystemResourceVectorsMatchPython(t *testing.T) {
	cases := []struct {
		resource string
		want     bool
	}{
		{"rmq_sys_x", true},
		{"CID_RMQ_SYS_g", true},
		{"Topic", false},
		{"", false},
	}
	for _, c := range cases {
		if got := IsSystemResource(c.resource); got != c.want {
			t.Fatalf("IsSystemResource(%q) = %v, want %v", c.resource, got, c.want)
		}
	}
}

func TestGetNamespaceFromResourceVectorsMatchPython(t *testing.T) {
	cases := []struct {
		resource, want string
	}{
		{"MQ_INST_XX%T", "MQ_INST_XX"},
		{"%RETRY%MQ_INST_XX%G", "MQ_INST_XX"},
		{"%RETRY%G", ""},
		{"rmq_sys_x", ""},
		{"", ""},
	}
	for _, c := range cases {
		if got := GetNamespaceFromResource(c.resource); got != c.want {
			t.Fatalf("GetNamespaceFromResource(%q) = %q, want %q", c.resource, got, c.want)
		}
	}
}

func TestWrapNamespaceAndRetry(t *testing.T) {
	if got := WrapNamespaceAndRetry("ns1", "GID"); got != "%RETRY%ns1%GID" {
		t.Fatalf("got %q", got)
	}
	// an empty group is returned as-is (Java short-circuits)
	if got := WrapNamespaceAndRetry("ns1", ""); got != "" {
		t.Fatalf("empty group must stay empty, got %q", got)
	}
}

func TestIsSysTopicAndIsSysConsumerGroup(t *testing.T) {
	if !IsSysTopic("rmq_sys_watermark") || IsSysTopic("MyTopic") || IsSysTopic("") {
		t.Fatal("IsSysTopic must be the rmq_sys_ prefix only")
	}
	// Deliberately weaker than IsSystemTopic: the fixed broker-topic set is not
	// consulted here (Java MixAll.isSysTopic behaves the same way).
	if IsSysTopic("TBW102") {
		t.Fatal("TBW102 has no rmq_sys_ prefix")
	}
	if !IsSysConsumerGroup("CID_RMQ_SYS_g") || IsSysConsumerGroup("CID_g") {
		t.Fatal("IsSysConsumerGroup must be the CID_RMQ_SYS_ prefix only")
	}
}
